name: 'Git Diff Sort'
description: 'Provides various Git diff outputs'
branding:
  color: 'orange'
  icon: 'filter'
inputs:
  meta_file_name:
    description: 'Name of the YAML file containing metadata'
    required: false
  keyword:
    description: 'Keyword to look for in the YAML file'
    required: false
  comparing_branch:
    description: 'Branch to compare with'
    required: false
  comparing_tag:
    description: 'Tag to compare with'
    required: false
  exclude_patterns:
    description: 'Comma separated list of directories to exclude from the git diff'
    required: false
  include_patterns:
    description: 'Comma separated list of directories to include in the git diff'
    required: false
  strip_path:
    description: 'Strip part of the folder name from the output'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        set -e
        python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Set Input Environment Variables
      id: set-env
      run: |
        echo "META_FILE_NAME=${{ inputs.meta_file_name }}" >> $GITHUB_ENV
        echo "KEYWORD=${{ inputs.keyword }}" >> $GITHUB_ENV
        echo "COMPARING_BRANCH=${{ inputs.comparing_branch }}" >> $GITHUB_ENV
        echo "COMPARING_TAG=${{ inputs.comparing_tag }}" >> $GITHUB_ENV
        echo "EXCLUDE_PATTERNS=${{ inputs.exclude_patterns }}" >> $GITHUB_ENV
        echo "INCLUDE_PATTERNS=${{ inputs.include_patterns }}" >> $GITHUB_ENV
        echo "STRIP_PATH=${{ inputs.strip_path }}" >> $GITHUB_ENV
      shell: bash

    - name: Run Python script
      id: git-diff
      run: |
        set -e
        PARAMS=""
        for INPUT in meta_file_name keyword comparing_branch comparing_tag exclude_patterns include_patterns strip_path; do
          INPUT_UPPERCASE=$(echo $INPUT | tr '[:lower:]' '[:upper:]')
          if [ -n "${!INPUT_UPPERCASE}" ]; then
            PARAMS="$PARAMS --$INPUT=${!INPUT_UPPERCASE}"
          fi
        done
        python3 ${{ github.action_path }}/src/main.py $PARAMS
      shell: bash


outputs:
  distinct_folders:
    value: ${{ steps.git-diff.outputs.distinct_folders }}
    description: 'Distinct folders from Git diff'
  folders_without_metadata:
    value: ${{ steps.git-diff.outputs.folders_without_metadata }}
    description: 'Folders without any metadata file'
  folders_sorted_alpha_inc:
    value: ${{ steps.git-diff.outputs.folders_sorted_alpha_inc }}
    description: 'Folders sorted alphabetically (incremental)'
  folders_sorted_alpha_dec:
    value: ${{ steps.git-diff.outputs.folders_sorted_alpha_dec }}
    description: 'Folders sorted alphabetically (decremental)'
  folders_sorted_meta_inc:
    value: ${{ steps.git-diff.outputs.folders_sorted_meta_inc }}
    description: 'Folders sorted based on metadata (incremental)'
  folders_sorted_meta_dec:
    value: ${{ steps.git-diff.outputs.folders_sorted_meta_dec }}
    description: 'Folders sorted based on metadata (decremental)'
  json:
    value: ${{ steps.git-diff.outputs.json }}
    description: 'All the different outputs in JSON format, you can access json.distinct_folders[]'
